//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentManagementSystemEntities : DbContext
    {
        public StudentManagementSystemEntities()
            : base("name=StudentManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchTable> BatchTables { get; set; }
        public virtual DbSet<Course_Registration> Course_Registrations { get; set; }
        public virtual DbSet<CourseTable> CourseTables { get; set; }
        public virtual DbSet<User_Registration> User_Registrations { get; set; }
    }
}
